-- TRANSFORM DATA

SELECT CAST(ORDER_ID AS CHAR(50)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY ORDER_ID CHAR(255);

SELECT CAST(BUYER_ID AS CHAR(50)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY BUYER_ID CHAR(255);

SELECT CAST(SUPPLIER_ID AS CHAR(50)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY SUPPLIER_ID CHAR(255);

SELECT CAST(Order_Value_USD AS DECIMAL(10,2)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Order_Value_USD DECIMAL(10,2);

SELECT CAST(Supplier_Reliability_Score AS DECIMAL(10,2)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Supplier_Reliability_Score DECIMAL(10,2);

SELECT CAST(Organization_ID AS CHAR(50)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Organization_ID CHAR(255);

SELECT CAST(Parameter_Change_Magnitude AS DECIMAL(10,2)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Parameter_Change_Magnitude DECIMAL(10,2);

SELECT CAST(Communication_Cost_MB AS DECIMAL(10,2)) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Communication_Cost_MB DECIMAL(10,2);

SELECT CAST(Order_Date AS DATETIME) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Order_Date DATETIME;

SELECT CAST(Order_Date AS DATE) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Order_Date DATE;

SELECT CAST(Dispatch_Date AS DATE) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Dispatch_Date DATE;

SELECT CAST(Delivery_Date AS DATE) FROM SPEDITION;
ALTER TABLE SPEDITION MODIFY Delivery_Date DATE;